Datacenter: "europe"
LogLevel: "error"

API:
  ListenAddress: "127.0.0.1"
  ListenPort: 1234

LDAP:
  Enabled: true
  InsecureSkipVerify: "false"
  URL: "ldaps://URL.local"
  BindDN: "cn=<user>,OU=<ou>,DC=<local>"
  BaseDN: "DC=<local>"
  Password: "<some_password>"

NetBox:
  URL: "https://netbox.local"
  APIKey: "<some_key>"

Build:
  Interval: "30m"