package syslog_test

import (
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/openconfig/ygot/ygot"

	syslogconvertors "github.com/criteo/data-aggregation-api/internal/convertor/syslog"
	"github.com/criteo/data-aggregation-api/internal/model/cmdb/syslog"
	"github.com/criteo/data-aggregation-api/internal/model/openconfig"
)

// syslogConfig is a syslog configuration as Netbox returns it, Device being an anonymous struct.
func syslogConfig(hostname string, servers ...syslog.Server) *syslog.Syslog {
	config := &syslog.Syslog{ServerList: servers}
	config.Device.Name = hostname
	return config
}

func TestSyslogToOpenconfig(t *testing.T) {
	primary, vip := "172.30.72.5", "172.30.78.91"

	tests := []struct {
		name string
		args *syslog.Syslog
		want *openconfig.System_Logging
	}{
		{
			name: "one remote server per address",
			args: syslogConfig("ra01-01-p01-da1-pnet.crto.io",
				syslog.Server{ServerAddress: primary},
				syslog.Server{ServerAddress: vip},
			),
			want: &openconfig.System_Logging{
				RemoteServer: map[string]*openconfig.System_Logging_RemoteServer{
					primary: {Host: &primary},
					vip:     {Host: &vip},
				},
			},
		},
		{
			name: "no syslog configuration",
			args: nil,
			want: nil,
		},
		{
			name: "no server",
			args: syslogConfig("ra01-01-p01-da1-pnet.crto.io", []syslog.Server{}...),
			want: nil,
		},
	}

	for _, test := range tests {
		out := syslogconvertors.SyslogToOpenconfig(test.args)
		if diff := cmp.Diff(out, test.want); diff != "" {
			t.Errorf("unexpected diff for '%s': %s\n", test.name, diff)
		}
	}
}

func TestSyslogToOpenconfigIsValid(t *testing.T) {
	device := &openconfig.Device{
		System: &openconfig.System{
			Logging: syslogconvertors.SyslogToOpenconfig(syslogConfig("ra01-01-p01-da1-pnet.crto.io",
				syslog.Server{ServerAddress: "172.30.72.5"},
			)),
		},
	}

	// ΛValidate is generated by ygot and checks the tree against the YANG schema; the Λ prefix keeps it
	// from colliding with YANG-derived names.
	if err := device.ΛValidate(); err != nil {
		t.Errorf("generated syslog configuration is not valid OpenConfig: %s", err)
	}
	if _, err := ygot.EmitJSON(device, &ygot.EmitJSONConfig{Format: ygot.RFC7951}); err != nil {
		t.Errorf("generated syslog configuration cannot be emitted as JSON: %s", err)
	}
}
